apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai-gateway-monitor
  namespace: ai-lab
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: ai-gateway
  namespaceSelector:
    matchNames:
      - ai-lab
  endpoints:
  - port: http-metrics
    path: /metrics
    interval: 15s
