# Stage 1: Build (Sin cambios)
FROM ubuntu:24.04 AS build
RUN apt-get update && apt-get install -y \
    build-essential cmake git libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
RUN git clone https://github.com/ggerganov/llama.cpp.git .
RUN mkdir build && cd build && \
    cmake .. -DGGML_NATIVE=ON -DGGML_OPENMP=ON -DLLAMA_CURL=ON && \
    cmake --build . --config Release --target llama-server

# Stage 2: Runtime
FROM ubuntu:24.04

# Instalamos dependencias base de runtime
RUN apt-get update && apt-get install -y \
    libcurl4 libgomp1 libstdc++6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/build/bin/llama-server /app/llama-server

COPY --from=build /app/build/bin/libmtmd.so.0 /usr/lib/libmtmd.so.0

RUN ldconfig

EXPOSE 8080
ENTRYPOINT ["/app/llama-server"]
